-- Clear existing games
DELETE FROM games;

-- Insert games data
INSERT INTO games (title, description, category, game_type, difficulty, is_active, order_index, instructions, estimated_time, tags, game_data) VALUES
('AI-Powered Exercise Generator', 'Generate personalized practice exercises using advanced AI. Choose your topic and difficulty level for tailored learning using authentic Life in UK content.', 'ai-generated', 'ai-exercises', 'intermediate', true, 1, 'Select your topic and difficulty level. The AI will generate personalized questions based on authentic Life in UK content.', 15, '["AI", "Personalized", "Adaptive", "Life in UK"]', '{"topics": ["British History", "Government & Politics", "Culture & Traditions", "Geography", "British Values", "Legal System"], "difficultyLevels": ["Beginner", "Intermediate", "Advanced"], "questionTypes": ["Multiple Choice", "Fill in the Blank", "True/False"]}'),

('True/False Challenge Games', 'Test your knowledge with True/False statements about UK facts, traditions, and values. Perfect for quick learning and building confidence!', 'true-false', 'true-false', 'beginner', true, 2, 'Read each statement carefully and decide if it''s True or False. Get immediate feedback with explanations.', 10, '["Quick Learning", "Instant Feedback", "UK Facts", "Confidence Building"]', '{"questionCount": 20, "timeLimit": 10, "topics": ["British History", "Government", "Culture", "Geography", "Values"]}'),

('Flip Cards Game', 'Click on cards to reveal the answers. Test your knowledge and mark cards as completed when you''ve mastered them.', 'flip-cards', 'flip-cards', 'beginner', true, 3, 'Click on any card to flip it and reveal the answer. Mark cards as ''Got it!'' when you''ve mastered the content.', 15, '["Interactive", "Self-Paced", "Memory Training", "Visual Learning"]', '{"cardTypes": ["Question/Answer", "Term/Definition", "Date/Event", "Person/Achievement"]}'),

('General Matching Game', 'Choose your difficulty (4, 6, 8, or 12 items) and match related concepts. Complete all variants to progress!', 'matching', 'matching-cards', 'intermediate', true, 4, 'Click one button from each of the two columns to make a match. Correct matches turn green and move to bottom of columns.', 12, '["Matching", "Critical Thinking", "Progressive Difficulty", "Conceptual Learning"]', '{"difficultyLevels": [4, 6, 8, 12], "nextGame": "Holiday Dates Matching"}'),

('UK Holiday Dates Matching Game', 'Match UK holidays with their celebration dates. Learn about traditional British celebrations, religious festivals, and cultural events.', 'matching', 'matching-cards', 'intermediate', true, 5, 'Match UK holidays with their celebration dates. Learn about traditional British celebrations.', 10, '["Holidays", "Dates", "British Culture", "Traditions"]', '{"holidays": ["Christmas", "Easter", "Guy Fawkes Night", "Burns Night", "Diwali", "Eid"], "nextGame": "Holiday Meanings Matching"}'),

('Holiday Meanings Matching Game', 'Match UK holidays with their meanings and significance. Understand the cultural, religious, and historical importance of each celebration.', 'matching', 'matching-cards', 'intermediate', true, 6, 'Match UK holidays with their meanings and significance.', 10, '["Holidays", "Meanings", "Cultural Significance", "Religious Events"]', '{"focus": "Cultural and religious significance of British holidays"}'),

('Sports Achievements Matching Game', 'Match British sports champions with their greatest accomplishments. Learn about Olympic heroes, World Cup winners, and sporting legends.', 'matching', 'matching-cards', 'intermediate', true, 7, 'Match British sports champions with their greatest accomplishments.', 12, '["Sports", "Achievements", "British Champions", "Olympic Heroes"]', '{"sports": ["Football", "Cricket", "Tennis", "Rugby", "Athletics", "Swimming"]}'),

('British Artists Matching Game', 'Match renowned British artists with their art forms. Explore centuries of artistic heritage from landscape painting to modern sculpture.', 'matching', 'matching-cards', 'intermediate', true, 8, 'Match renowned British artists with their art forms.', 12, '["Art", "British Artists", "Cultural Heritage", "Art Forms"]', '{"artForms": ["Painting", "Sculpture", "Literature", "Music", "Theatre", "Architecture"]}'),

('UK Age Requirements Matching Game', 'Match legal activities with their correct age requirements. Learn about employment, driving, voting, and other important legal milestones in the UK.', 'matching', 'matching-cards', 'intermediate', true, 9, 'Match legal activities with their correct age requirements.', 10, '["Legal System", "Age Requirements", "Citizenship", "Rights and Responsibilities"]', '{"activities": ["Voting", "Driving", "Working", "Marriage", "Alcohol", "Smoking"]}'),

('British Leaders Matching Game', 'Match British monarchs, prime ministers, and historical figures with their achievements. Explore leadership throughout British history.', 'matching', 'matching-cards', 'intermediate', true, 10, 'Match British monarchs, prime ministers, and historical figures with their achievements.', 15, '["History", "Leadership", "Monarchs", "Prime Ministers", "Political Figures"]', '{"leaders": ["Monarchs", "Prime Ministers", "Historical Figures", "Political Leaders"]}'),

('UK Cultural Awards Matching Challenge', 'Match British cultural awards with their categories. Learn about prestigious honors in theatre, music, literature, and the arts including BRIT Awards, Turner Prize, Booker Prize, and more.', 'matching', 'matching-cards', 'advanced', true, 11, 'Match British cultural awards with their categories.', 15, '["Cultural Awards", "Arts", "Literature", "Music", "Theatre", "Prestigious Honors"]', '{"awards": ["BRIT Awards", "Turner Prize", "Booker Prize", "Olivier Awards", "BAFTA", "Mercury Prize"]}'),

('Acts, Treaties & Bills Triple Match Challenge', 'Match important British acts, treaties, and bills with their years and purposes. Learn about landmark legislation that shaped UK history.', 'matching', 'matching-cards', 'advanced', true, 12, 'Select one item from each of the three columns to make a complete match. All three selections must relate to the same concept.', 20, '["Legislation", "History", "Triple Match", "Advanced", "Legal Documents"]', '{"columns": ["Acts/Treaties/Bills", "Years", "Purposes"], "complexity": "triple-match"}'),

('Sports Heroes Triple Match Challenge', 'Choose your challenge level (4, 6, 8, or 12 heroes) and match British sports legends with their sports and achievements. Complete all variants to unlock the next challenge!', 'matching', 'matching-cards', 'advanced', true, 13, 'Match British sports legends with their sports and achievements.', 18, '["Sports Heroes", "Triple Match", "Advanced", "British Legends", "Achievements"]', '{"columns": ["Sports Heroes", "Sports", "Achievements"], "difficultyLevels": [4, 6, 8, 12], "nextGame": "Justice System Triple Match"}'),

('UK Justice System Triple Match Challenge', 'Match courts with their jurisdictions and regions. Learn about the complex UK justice system across England & Wales, Scotland, and Northern Ireland.', 'matching', 'matching-cards', 'advanced', true, 14, 'Match courts with their jurisdictions and regions.', 20, '["Justice System", "Courts", "Jurisdictions", "Legal System", "Triple Match"]', '{"columns": ["Courts", "Jurisdictions", "Regions"], "regions": ["England & Wales", "Scotland", "Northern Ireland"]}'),

('UK Religion & Demographics Triple Match Challenge', 'Match religions with their percentages and ethnic compositions. Understand the UK''s diverse religious and demographic landscape.', 'matching', 'matching-cards', 'advanced', true, 15, 'Match religions with their percentages and ethnic compositions.', 18, '["Religion", "Demographics", "Diversity", "Statistics", "Triple Match"]', '{"columns": ["Religions", "Percentages", "Ethnic Compositions"]}'),

('UK International Memberships Triple Match Challenge', 'Match international organizations with the UK''s role and membership details. Learn about Britain''s place in global institutions.', 'matching', 'matching-cards', 'advanced', true, 16, 'Match international organizations with the UK''s role and membership details.', 20, '["International Relations", "Organizations", "Global Institutions", "Triple Match"]', '{"columns": ["International Organizations", "UK Role", "Membership Details"]}'),

('British Battles & Wars Triple Match Challenge', 'Match battles with their years and participants. Explore major military conflicts throughout British history from medieval times to modern warfare.', 'matching', 'matching-cards', 'advanced', true, 17, 'Match battles with their years and participants.', 22, '["Military History", "Battles", "Wars", "Historical Events", "Triple Match"]', '{"columns": ["Battles", "Years", "Participants"], "periods": ["Medieval", "Tudor", "Civil War", "World Wars", "Modern"]}'),

('British Rulers & Religions Triple Match Challenge', 'Match rulers with their reign periods and religious affiliations. Explore the complex relationship between monarchy and religion in British history.', 'matching', 'matching-cards', 'advanced', true, 18, 'Match rulers with their reign periods and religious affiliations.', 20, '["Monarchy", "Religion", "Historical Rulers", "Triple Match", "Complex Relationships"]', '{"columns": ["Rulers", "Reign Periods", "Religious Affiliations"]}'),

('British Prime Ministers Triple Match Challenge', 'Match Prime Ministers with their terms and historical periods. Learn about political leadership throughout British democratic history.', 'matching', 'matching-cards', 'advanced', true, 19, 'Match Prime Ministers with their terms and historical periods.', 18, '["Prime Ministers", "Political History", "Democratic Leadership", "Triple Match"]', '{"columns": ["Prime Ministers", "Terms", "Historical Periods"]}'),

('UK Places of Interest Triple Match Challenge', 'Match places with their regions and descriptions. Discover iconic locations across England, Scotland, Wales, and Northern Ireland.', 'matching', 'matching-cards', 'advanced', true, 20, 'Match places with their regions and descriptions.', 20, '["Geography", "Places of Interest", "UK Regions", "Landmarks", "Triple Match"]', '{"columns": ["Places", "Regions", "Descriptions"], "regions": ["England", "Scotland", "Wales", "Northern Ireland"]}'),

('Traditional Foods Triple Match Challenge', 'Match dishes with their regions and ingredients. Explore British culinary heritage across all four countries of the UK.', 'matching', 'matching-cards', 'advanced', true, 21, 'Match dishes with their regions and ingredients.', 18, '["Food", "Culinary Heritage", "Regional Dishes", "Ingredients", "Triple Match"]', '{"columns": ["Dishes", "Regions", "Ingredients"]}'),

('UK Constituent Countries Triple Match Challenge', 'Match countries with their capitals and symbols. Test your knowledge of UK geography, culture, and national identity including patron saints, symbols, flags, and major cities.', 'matching', 'matching-cards', 'advanced', true, 22, 'Match countries with their capitals and symbols.', 20, '["UK Geography", "Constituent Countries", "Capitals", "National Symbols", "Triple Match"]', '{"columns": ["Countries", "Capitals", "Symbols"], "countries": ["England", "Scotland", "Wales", "Northern Ireland"]}'),

('UK Parliament & Devolution Triple Match Challenge', 'Match regions with their parliaments and powers. Learn about UK government structure, devolution, and democratic institutions including Westminster, Holyrood, Senedd, and Stormont.', 'matching', 'matching-cards', 'advanced', true, 23, 'Match regions with their parliaments and powers.', 22, '["Parliament", "Devolution", "Government Structure", "Democratic Institutions", "Triple Match"]', '{"columns": ["Regions", "Parliaments", "Powers"], "parliaments": ["Westminster", "Holyrood", "Senedd", "Stormont"]}');
